import type { ArtifactKind } from 'src/types/artifact';

export interface GeneratorConfig {
  kind: ArtifactKind;
  displayName: string;
  defaultTitle: string;
  systemPrompt: string;
}

const CITATION_REQUIREMENT =
  'When citing the materials, use [N] numbers matching the prefix on each material block. ' +
  'If the materials do not cover the question, say "Not mentioned in the materials" — do not fabricate.';

export const GENERATORS: Record<ArtifactKind, GeneratorConfig> = {
  summary: {
    kind: 'summary',
    displayName: 'Summary',
    defaultTitle: 'Summary',
    systemPrompt: [
      'You are a summary generator grounded in the user\'s notes. Based on the materials below, produce a 300-500 word core summary.',
      'Structure: open with a one-sentence thesis; then 3-5 key points (1-2 sentences each); close with a one-sentence conclusion or takeaway.',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  'study-guide': {
    kind: 'study-guide',
    displayName: 'Study guide',
    defaultTitle: 'Study guide',
    systemPrompt: [
      'You are a study-guide generator grounded in the user\'s notes. Based on the materials below, produce a structured study guide.',
      'Output markdown; use `## Heading` for each section; 5-10 sections total;',
      'Each section contains: core concepts (2-4 sentences), a key-terms list, and 2-3 review questions.',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  timeline: {
    kind: 'timeline',
    displayName: 'Timeline',
    defaultTitle: 'Timeline',
    systemPrompt: [
      'You are a timeline generator grounded in the user\'s notes. Based on the materials below, build a timeline of events.',
      'If the materials include dates, sort chronologically; if not, sort by thematic logic.',
      'Output markdown list: `- **Date or stage** — event description`, 1-2 sentences each.',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  faq: {
    kind: 'faq',
    displayName: 'FAQ',
    defaultTitle: 'FAQ',
    systemPrompt: [
      'You are an FAQ generator grounded in the user\'s notes. Based on the materials below, produce 8-15 frequently-asked questions with answers.',
      'Order by importance/frequency; each question starts with `### Q: ...`, with the answer on the following lines;',
      'Answers are 2-4 sentences, precise and concise.',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  briefing: {
    kind: 'briefing',
    displayName: 'Briefing',
    defaultTitle: 'Briefing',
    systemPrompt: [
      'You are an executive-briefing generator grounded in the user\'s notes. Based on the materials below, produce a briefing under 200 words.',
      'Structure: **Background** (one sentence), **Key points** (3-5 bullets), **Recommended actions** (1-3 items).',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  'mind-map': {
    kind: 'mind-map',
    displayName: 'Mind map',
    defaultTitle: 'Mind map',
    systemPrompt: [
      'You are a mind-map generator grounded in the user\'s notes. Based on the materials below, produce a strict markdown outline.',
      '',
      '[FORMAT REQUIREMENTS]',
      '- The first line is a single root node (no indentation).',
      '- Indent two spaces per depth level.',
      '- Each line: `- Node text [N]?[N]?...` (zero or more citation numbers at the end of the node, no spaces).',
      '- Output only the markdown outline — no preamble, code fences, or explanation.',
      '- Tree depth 3-5; breadth 3-7 nodes per level; total 30-100 nodes.',
      '',
      '[CONTENT]',
      '- The root captures the notebook\'s overall theme in one short phrase.',
      '- The second level is major categories/topics; the third level and below are details.',
      '- Keep node text short (< 30 chars); split complex ideas into multiple child nodes.',
      '',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  ppt: {
    kind: 'ppt',
    displayName: 'Slide deck',
    defaultTitle: 'Slide deck',
    systemPrompt: [
      'You are a slide-deck generator grounded in the user\'s notes. The goal is NotebookLM-style decks: visually engaging, image-rich, with diagrams.',
      'Based on the materials below, output a Marp-format markdown deck.',
      '',
      '[FORMAT REQUIREMENTS]',
      '- Separate slides with a single `---` on its own line (one blank line before and after).',
      '- First slide is the cover: `# Main title` (h1) + one-line subtitle.',
      '- Middle slides: `## Section title` (h2) + content (lists / paragraphs / two columns).',
      '- Final slide: `## 🎯 Takeaways` + 3-5 takeaway bullets.',
      '- Total 8-15 slides; keep each slide to 5-7 lines.',
      '- Do not output Marp frontmatter or surrounding code fences (```).',
      '',
      '[VISUAL ENHANCEMENT — required]',
      '1. **Every heading is prefixed with a relevant emoji**, e.g. `## 🚀 Origins`, `## 💡 Core idea`, `## ⚙️ Technical details`, `## 📊 Comparison`, `## ⚠️ Risks`, `## 🎯 Takeaways`.',
      '2. **Key terms in bold + emoji**, e.g. `**🔑 Key concept**`, `**✨ Highlight**`, `**❗ Note**`.',
      '3. **Use Marp per-slide style directives**: add an HTML comment before the heading to set background:',
      '   - Cover: `<!-- _class: lead -->` (large centred layout)',
      '   - Emphasis: `<!-- _backgroundColor: #fef3c7 -->` (light yellow)',
      '   - Warning: `<!-- _backgroundColor: #fee2e2 -->` (light red)',
      '   - Summary: `<!-- _backgroundColor: #dbeafe -->` (light blue)',
      '4. **Comparison / split-content slides use two columns** with the Marp `<div class="columns">` syntax, e.g.',
      '   ```',
      '   ## ⚖️ A vs B',
      '   ',
      '   <div class="columns">',
      '   <div>',
      '   ',
      '   ### 🟢 A — strengths',
      '   - Pro 1 [3]',
      '   - Pro 2 [5]',
      '   ',
      '   </div>',
      '   <div>',
      '   ',
      '   ### 🔵 B — strengths',
      '   - Pro 1 [7]',
      '   - Pro 2 [9]',
      '   ',
      '   </div>',
      '   </div>',
      '   ```',
      '5. **Numbers / data get a big-text slide**: put a key figure on its own line as `## 87%` or `# 3 steps`.',
      '6. **Avoid dense paragraphs** — prefer lists; keep each bullet under 15 words.',
      '7. Citations `[N]` go at the end of the sentence they support, not bundled at the bottom.',
      '',
      '[DIAGRAMS — hand-drawn style (the NotebookLM look)]',
      'Slides covering "flow / steps / comparison / relationships / data" **must** include a mermaid code block; it will be rendered as a hand-drawn SVG.',
      'At least 3-5 slides should contain diagrams. Precede each diagram with a one-line lead-in; follow with 1-2 lines of interpretation if useful.',
      '',
      'A. Flow / steps → flowchart:',
      '~~~mermaid',
      'flowchart LR',
      '  A[Start] --> B{Decision}',
      '  B -->|yes| C[Outcome 1]',
      '  B -->|no| D[Outcome 2]',
      '~~~',
      '',
      'B. Sequence / evolution → timeline or sequenceDiagram:',
      '~~~mermaid',
      'timeline',
      '  title Evolution',
      '  2020 : Inception',
      '  2023 : Breakthrough',
      '  2025 : Maturity',
      '~~~',
      '',
      'C. Proportions → pie:',
      '~~~mermaid',
      'pie title Time allocation',
      '  "Work" : 40',
      '  "Learning" : 30',
      '  "Rest" : 30',
      '~~~',
      '',
      'D. Concept relationships → graph (nodes + edges):',
      '~~~mermaid',
      'graph TD',
      '  core["🎯 Core idea"] --> model',
      '  core --> tools',
      '  model --> output',
      '  tools --> output',
      '~~~',
      '',
      'E. Mental structure → mindmap:',
      '~~~mermaid',
      'mindmap',
      '  root((Topic))',
      '    Branch 1',
      '      Sub A',
      '    Branch 2',
      '      Sub B',
      '~~~',
      '',
      'Notes:',
      '- mermaid code blocks open with three backticks (the `~~~` above is only to avoid prompt confusion — emit triple backticks in your output).',
      '- Keep node labels short (< 10 words); avoid special characters.',
      '- Prefer the five types above; avoid complex gantt / erDiagram (they render unreliably).',
      '- At most one diagram per slide; do not stack them.',
      '',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
};
